---
abstract: 'Socket.IO Plack app'
author:
  - 'Viacheslav Tykhanovskyi <vti@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PocketIO
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  AnyEvent: 0
  Carp: 0
  JSON: 0
  Protocol::SocketIO: 0
  Protocol::WebSocket: 0.009006
  Scalar::Util: 0
  Test::More: 0
  Test::TCP: 0
  perl: 5.8.7
resources:
  bugtracker: http://github.com/vti/pocketio/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/vti/pocketio/
version: 0.12
